In [76]:
import requests
from urllib.parse import quote
import pandas as pd

In [77]:
# API 키 로드
with open('key/서울부동산key.txt') as file:
    부동산_key = file.read()

In [78]:
# 한번에 1000개 데이터밖에 불러오지못해서 반복문을 사용해 데이터 불러오기
a = 1
b = 1000
data = []
for i in range(26):
    base_url = f'http://openapi.seoul.go.kr:8088/{quote(부동산_key)}/json/landBizInfo/{a}/{b}/'
    url = requests.get(base_url).json()
    df = pd.DataFrame(url['landBizInfo']['row'])
    data.append(df)
    a += 1000
    b += 1000
base_url1 = f'http://openapi.seoul.go.kr:8088/{quote(부동산_key)}/json/landBizInfo/26001/26608/'
url1 = requests.get(base_url1).json()
df1 = pd.DataFrame(url1['landBizInfo']['row'])
data.append(df1)
df2 = pd.concat(data, ignore_index=True)

In [79]:
# 데이터 확인
df2.head()

,SYS_REGNO,SGG_CD,BJDONG_CD,SGG_NM,BJDONG_NM,LAND_GBN,BOBN,BUBN,ADDRESS,RA_REGNO,...,CMP_NM,TELNO,STS_GBN,BEGIN_DE,END_DE,RNUM,ROAD_CD,BLDG_LOC,BLDG_BOBN,BLDG_BUBN
0,113802008000179,11380,1138010800,은평구,역촌동,1,0028,0015,서울특별시 은평구 진흥로5길 4 (역촌동),다92340000-3128,...,신화공인중개사사무소,359-1216,영업중,,,147,113804133285,0,4,0
1,113802008000183,11380,1138010800,은평구,역촌동,1,0017,0005,서울특별시 은평구 진흥로9길 8-18 (역촌동),다92340000-3132,...,예스공인중개사사무소,386-5566,영업중,,,148,113804133289,0,8,18
2,113802008000586,11380,1138010300,은평구,불광동,1,0170,0061,서울특별시 은평구 불광로22길 28-13 (불광동),다92340000-3517,...,대용공인중개사사무소,02-385-8760,영업중,,,149,113804133086,0,28,13
3,113802008000596,11380,1138010800,은평구,역촌동,1,0024,0007,서울특별시 은평구 진흥로1길 54 1층 좌측 (역촌동),다92340000-3531,...,대지공인중개사사무소,02-355-4401,영업중,,,150,113804133280,0,54,0
4,113802008000598,11380,1138010800,은평구,역촌동,1,0040,0009,서울특별시 은평구 진흥로1길 24 (역촌동),다92340000-3533,...,현대공인중개사사무소,382-5050,영업중,,,151,113804133280,0,24,0

In [80]:
# 데이터프레임 키확인
df2.keys()

Index(['SYS_REGNO', 'SGG_CD', 'BJDONG_CD', 'SGG_NM', 'BJDONG_NM', 'LAND_GBN',
       'BOBN', 'BUBN', 'ADDRESS', 'RA_REGNO', 'RDEALER_NM', 'CMP_NM', 'TELNO',
       'STS_GBN', 'BEGIN_DE', 'END_DE', 'RNUM', 'ROAD_CD', 'BLDG_LOC',
       'BLDG_BOBN', 'BLDG_BUBN'],
      dtype='object')

In [81]:
# 필요없는 컬럼 제거
df2.drop(columns=['SYS_REGNO', 'SGG_CD', 'BJDONG_CD', 'LAND_GBN', 'BOBN', 'BUBN', 'BEGIN_DE', 'END_DE', 'RNUM', 'ROAD_CD', 'BLDG_LOC', 'BLDG_BOBN', 'BLDG_BUBN', 'STS_GBN', 'SGG_NM', 'BJDONG_NM'], inplace=True)
df2.dropna(inplace=True)
df2.tail()

,ADDRESS,RA_REGNO,RDEALER_NM,CMP_NM,TELNO
26603,서울특별시 마포구 독막로 84 (상수동),92380000-2936,구은숙,롯데부동산공인중개사사무소,325-0053
26604,"서울특별시 마포구 월드컵북로 233 제1상가동 105호 (성산동, 성산시영아파트)",92380000-2945,오근오,성산부동산공인중개사사무소,305-5449
26605,서울특별시 마포구 토정로31길 57 (대흥동),92380000-01071,손유아,부동산씨티공인중개사사무소,703-5011
26606,"서울특별시 마포구 대흥로 186-1 , 제1층 (대흥동)",92380000-01006,윤용철,신흥공인중개사사무소,02-704-3579
26607,서울특별시 마포구 신촌로16길 34 (노고산동),가92380000-00769,김학봉,백산부동산중개사무소,718-8469

In [82]:
# 결측치 확인
df2.isna().sum()

ADDRESS       0
RA_REGNO      0
RDEALER_NM    0
CMP_NM        0
TELNO         0
dtype: int64

In [83]:
# csv파일로 저장
df2.to_csv('data/서울부동산.csv', index=False, encoding='utf-8')